version: '3.8'

services:
  frontend:
    image: tap04ek/ss-frontend  # ← вместо build
    ports: ["3000:3000"]
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on: [backend]

  backend:
    image: tap04ek/ss-backend   # ← вместо build
    ports: ["8000:8000"]
